name: Build driver
on:
  push:
    branches:
      - 'master'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: raspios_lite_arm64:latest
        cpu: cortex-a7
        image_additional_mb: 1500
        bind_mount_repository: true
        commands: |
            apt-get update
            apt-get install -y build-essential meson ninja-build libssl-dev openssl libyaml-dev python3-yaml python3-ply python3-jinja2 libudev-dev libevent-dev libdrm-dev python3 
            meson build
            ninja -C build install

    - run: find .

    - uses: actions/upload-artifact@master
      with:
        name: Shared libs
        path: build/*/*.so

    # Push to dev release on pushes to master
    - uses: pyTooling/Actions/releaser@r0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: 'Dev'
        rm: true
        files: |
          build/*/*.so
      if: github.event_name == 'push'

    # Push to actual release, if tagged
    - uses: softprops/action-gh-release@v1
      with:
        files: |
          build/*/*.so
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
